APP_KEY = "BHAK.JAS"       
GEMINI_API_KEY = "AIzaSyB2ndBcm07hm7r9tk-V-xeX1JOVNhsNNCo"
CSE_API_KEY = "AIzaSyBUJBEr8BJkHcndOzbNDdIXuXS-5lEjBcQ"
CSE_CX = "f26832f05fe204a05"
FRED_API_KEY = "2b38e8e230c6a9c1c60f58674e80eeea"
